---
- name: Using our new module
  hosts: localhost

  tasks:
          - name: New Module
            my_new_test_module:
                    name: You say goodbye
                    new: True
            register: results

          - debug:
                  var: results.message
