---
- name: First Error handler
  hosts: planet_express

  tasks:
          - block:
                  - shell: "echo 'My single task run' > example.txt"
                  - shell: "echo 'My second task run' >> example.txt"
                  - shell: "echo 'My third task run' >> example.txt"
