---
- name: First Error handler
  hosts: planet_express

  tasks:
          - block:
                  - shell: "echo 'My single task run' > example.txt"
                  - shell: "echo 'My second task run' >> example.txt"
                  - shell: "/bin/false" #This always fails
            rescue:
                    - shell: "echo 'My rescue code ran. Maybe it undoes whatever the block \
                      tried to do' >> example.txt"
            always:
                    - shell: "echo 'This always runs. Maybe it is a commit, or an \
                      entry in a log' >> example.txt"
