---
- name: Network Agnostic Playbook
  hosts: ~^arista
  gather_facts: no

  vars:
          dnsserver: "8.8.8.8"
  tasks:
          - name: CONFIGURE DNS
            cli_config:
                    config: ip name-server {{ dnsserver }}

          - name: CHECK CONFIGURATION
            cli_command:
                    command: show run | i ip name-server
            register: results

          - name: PRINT OUTPUT TO SCREEN
            debug:
                    var: results.stdout
            tags:
                    - never
                    - showresults
            # Lets create a new variable based on dynamic data
            # If our command worked, we know it should respond with ip name-server vrf default www.xxx.yy.zzz
            # where www.xxx.yy.zzzz should be the IP address passed to the playbook for dnsserver
          - set_fact:
                  expected_output: "ip name-server vrf default {{ dnsserver }}"
                  #expected_output: "ip name-server vrf default 8.8.8.9"

            # now perform the check
          - fail:
                  msg: failing
            when: expected_output not in results.stdout
