---
- name: Agnostic Net Example
  hosts: all
  gather_facts: false
  vars:
          ansible_connection: network_cli
          ansible_network_os: eos
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: admin
          ansible_ssh_pass: alta3

  tasks:
          # run a show run command and save what is returned by the command
          - name: run show version on remove devices
            cli_command:
                    command: show version
            register: results


          # print out the variable results
          - name: print out the show version
            debug:
                    var: results.stdout_lines
