---
- name: Another network playbok example
  # The line below calls our group that does not have any clear-text passwords
  hosts: aristaswitchessecure
  # gather_facts ALWAYS runs on setup.py (server module)
  gather_facts: no

  # Instead we will store our encrypted information within a YAML file, vault.yml
  vars_files:
          - vault.yml

  tasks:
          #if we run thi and have gather_facts set to no, then ansible_facts will be about our network devs
          - name: Harvest Arista facts
            eos_facts:
            when: ansible_network_os == 'eos'
